#!/bin/sh

# ----------------------
# symlink configs

ln -s ~/.dotfiles/.gemrc ~/.gemrc

ln -s ~/.dotfiles/.gitconfig ~/.gitconfig
ln -s ~/.dotfiles/.githelpers ~/.githelpers
ln -s ~/.dotfiles/.gitignore ~/.gitignore

ln -s ~/.dotfiles/.powconfig ~/.powconfig
ln -s ~/.dotfiles/.pryrc ~/.pryrc
ln -s ~/.dotfiles/.zshrc ~/.zshrc

# ----------------------
# for the mongo database

mkdir ~/.dotfiles/local_db

# ----------------------
# bundler

mkdir ~/.bundle
ln -s ~/.dotfiles/.bundle_config ~/.bundle/config
